services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iwashere
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: iwashere
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/iwashere
    depends_on:
      - postgres